apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: homework-week4
  annotations:
{{/*    kubernetes.io/ingress.class: "nginx"*/}}
{{/*    nginx.ingress.kubernetes.io/rewrite-target: "/api/"*/}}
{{/*    nginx.ingress.kubernetes.io/app-root: "/api"*/}}
{{/*    nginx.ingress.kubernetes.io/use-regex: "true"*/}}
spec:
  ingressClassName: "nginx"
  rules:
    - host: homework-fe.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
{{/*          - path: /static/**/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: frontend-service*/}}
{{/*                port:*/}}
{{/*                  number: 3000*/}}