apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.labels.serviceLabel }}
  namespace: {{ .Values.frontend.metadata.namespace }}
spec:
  selector:
    app: {{ .Values.frontend.labels.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
  type: {{ .Values.frontend.service.type }}
